In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
print(*sent, sep = '\n')

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good


In [9]:
voc_size = 10000

##### One-Hot Representation

In [10]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[1791, 944, 1329, 3471], [1791, 944, 1329, 401], [1791, 9520, 1329, 8045], [8530, 4863, 9471, 7163, 2681], [8530, 4863, 9471, 7163, 6621], [9742, 1791, 9779, 1329, 4560], [5122, 1104, 5069, 7163]]


### Word Embedding Representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [14]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
embedded_docs

array([[   0,    0,    0,    0, 1791,  944, 1329, 3471],
       [   0,    0,    0,    0, 1791,  944, 1329,  401],
       [   0,    0,    0,    0, 1791, 9520, 1329, 8045],
       [   0,    0,    0, 8530, 4863, 9471, 7163, 2681],
       [   0,    0,    0, 8530, 4863, 9471, 7163, 6621],
       [   0,    0,    0, 9742, 1791, 9779, 1329, 4560],
       [   0,    0,    0,    0, 5122, 1104, 5069, 7163]], dtype=int32)

In [15]:
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.predict(embedded_docs)[0]

array([[-0.03776853,  0.01786157,  0.03421963,  0.01971864, -0.03077263,
        -0.04855493,  0.04386801, -0.03522891, -0.02829063,  0.04064773],
       [-0.03776853,  0.01786157,  0.03421963,  0.01971864, -0.03077263,
        -0.04855493,  0.04386801, -0.03522891, -0.02829063,  0.04064773],
       [-0.03776853,  0.01786157,  0.03421963,  0.01971864, -0.03077263,
        -0.04855493,  0.04386801, -0.03522891, -0.02829063,  0.04064773],
       [-0.03776853,  0.01786157,  0.03421963,  0.01971864, -0.03077263,
        -0.04855493,  0.04386801, -0.03522891, -0.02829063,  0.04064773],
       [-0.01792032, -0.03953097,  0.04022136, -0.04158652,  0.01506057,
        -0.01307833,  0.0074862 ,  0.03976656, -0.04628096,  0.04246649],
       [-0.02433014, -0.00291765,  0.02223765, -0.01278658,  0.04815659,
         0.00698117, -0.02255224,  0.00209023, -0.02354149,  0.04326003],
       [-0.0346053 ,  0.03149668,  0.027962  , -0.00677636,  0.0492377 ,
         0.00933035,  0.04887339, -0.00491057

In [23]:
model.predict(embedded_docs)

array([[[-0.03776853,  0.01786157,  0.03421963,  0.01971864,
         -0.03077263, -0.04855493,  0.04386801, -0.03522891,
         -0.02829063,  0.04064773],
        [-0.03776853,  0.01786157,  0.03421963,  0.01971864,
         -0.03077263, -0.04855493,  0.04386801, -0.03522891,
         -0.02829063,  0.04064773],
        [-0.03776853,  0.01786157,  0.03421963,  0.01971864,
         -0.03077263, -0.04855493,  0.04386801, -0.03522891,
         -0.02829063,  0.04064773],
        [-0.03776853,  0.01786157,  0.03421963,  0.01971864,
         -0.03077263, -0.04855493,  0.04386801, -0.03522891,
         -0.02829063,  0.04064773],
        [-0.01792032, -0.03953097,  0.04022136, -0.04158652,
          0.01506057, -0.01307833,  0.0074862 ,  0.03976656,
         -0.04628096,  0.04246649],
        [-0.02433014, -0.00291765,  0.02223765, -0.01278658,
          0.04815659,  0.00698117, -0.02255224,  0.00209023,
         -0.02354149,  0.04326003],
        [-0.0346053 ,  0.03149668,  0.027962  , -0.0